### ISSUE TITLE
Leaflet Marker icons

### ISSUE THREAD

**Issue by dimaursu** [moklick/generator-leaflet#5]
Adding a maker will not use the default maker icon: it looks for them here: 
http://localhost:9000/lib/scripts/images/marker-icon.png

**Comment by dimaursu** [comment]
http://localhost:9000/lib/images/marker-icon.png 
this is the right url.

**Comment by moklick** [comment]
@dimaursu thanks for the info. A gulptask for the leaflet images is missing. I will add that tomorrow

**Comment by dimaursu** [comment]
On 11/28/2014 01:34 AM, moklick wrote:

> @dimaursu https://github.com/dimaursu thanks for the info. A gulptask
> for the leaflet images is missing. I will add that tomorrow

Oh. I just made another icon template, and changed the urls :)
