### ISSUE TITLE
leaflet js and css not loading

### ISSUE THREAD

**Issue by eczajk1** [moklick/generator-leaflet#6]
I am still new to a lot of this, but after I run `yo` and `gulp watch`, none of the leaflet stuff gets copied to "app/lib/", which is where index.html says it should be.

I included only jQuery in my app.

**Comment by moklick** [comment]
Hey! After running `gulp watch`, you should see a running version at http://localhost:9000. I am not sure right now, but maybe you just have to run `gulp` before. I can check it tomorrow if it's still not working for you.

**Comment by eczajk1** [comment]
Yeah ... i'm not sure what I was doing wrong before.  Thanks!
